apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo:4.1.1-xenial
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always

