apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-gateway-ingress
spec:
  rules:
    - host: 6fvb56kis4.lb.c4.gra.k8s.ovh.net
      http:
        paths:
          - path: /
            backend:
              serviceName: client-gateway
              servicePort: 8080
