apiVersion: v1
kind: Service
metadata:
  labels:
    app: lfeoperatorfabric
    service: registry
  name: registry
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  - name: "4001"
    port: 4001
    targetPort: 5005
  selector:
    service: registry
