apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lfeoperatorfabric
    service: thirds
  name: thirds-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
