kind: Deployment
apiVersion: apps/v1
metadata:
  name: cards-publication
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cards-consultation
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-gateway
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config
spec:
  replicas: 2
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: registry
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: time
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
spec:
  replicas: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: thirds
spec:
  replicas: 1 # Todo update when stateless
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-ui
spec:
  replicas: 2